name: 每日同步原作者源码

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-code:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取 kalicyh 分支
        uses: actions/checkout@v7
        with:
          ref: kalicyh
          fetch-depth: 0

      - name: 配置Git用户信息
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: 合并 upstream/dev 到 kalicyh
        run: |
          git remote add upstream https://github.com/Sesame-AG/Sesame-AG.git
          git fetch upstream dev
          git merge upstream/dev --no-edit
          git push origin HEAD:kalicyh
